const LEADS_NEW_STATUS = 1
const LEADS_FOLLOW_UP_STATUS = 2
const LEADS_SURVEY_REQUEST_STATUS = 3
const LEADS_SURVEY_REJECTED_STATUS = 4
const LEADS_SURVEY_COMPLETE_STATUS = 5
const LEADS_FINAL_FOLLOW_UP_STATUS = 6

const SURVEY_STATUS_ON_REVIEW = "On Review"
const SURVEY_STATUS_ACCEPTED = "Accepted"
const SURVEY_STATUS_REJECTED= "Rejected"

module.exports = {
    LEADS_NEW_STATUS,
    LEADS_FOLLOW_UP_STATUS,
    LEADS_SURVEY_REJECTED_STATUS,
    LEADS_SURVEY_REQUEST_STATUS,
    LEADS_SURVEY_COMPLETE_STATUS,
    LEADS_FINAL_FOLLOW_UP_STATUS,
    SURVEY_STATUS_ON_REVIEW,
    SURVEY_STATUS_ACCEPTED,
    SURVEY_STATUS_REJECTED
}


