const LEADS_NEW_STATUS = 1
const LEADS_FOLLOW_UP_STATUS = 2
const LEADS_SURVEY_REQUEST_STATUS = 3
const LEADS_SURVEY_REJECTED_STATUS = 4
const LEADS_SURVEY_COMPLETE_STATUS = 5
const LEADS_FINAL_FOLLOW_UP_STATUS = 6
const LEADS_DEAL_STATUS = 7
const LEADS_NO_DEAL_STATUS = 8

const SURVEY_STATUS =["On Review", "Accepted", "Rejected", "Completed"]

const FOLLOW_UP_MESSAGE_FOR_FINAL_PROPOSAL = "Follow Up Final Proposal"

const UPLOADS_FOLDER_PATH_PREFIX = "uploads/"

const HASH_SALT_ROUNDS = 10;

module.exports = {
    LEADS_NEW_STATUS,
    LEADS_FOLLOW_UP_STATUS,
    LEADS_SURVEY_REJECTED_STATUS,
    LEADS_SURVEY_REQUEST_STATUS,
    LEADS_SURVEY_COMPLETE_STATUS,
    LEADS_FINAL_FOLLOW_UP_STATUS,
    LEADS_DEAL_STATUS,
    LEADS_NO_DEAL_STATUS,
    SURVEY_STATUS,
    UPLOADS_FOLDER_PATH_PREFIX,
    FOLLOW_UP_MESSAGE_FOR_FINAL_PROPOSAL,
    HASH_SALT_ROUNDS
}


